---


- name: Clone repository to userhome
  git:
    repo: "{{ lcsh_repourl }}"
    dest: "{{ lcsh_userhome }}/letsencrypt.sh"
    version: "{{ lcsh_commit }}"
    # force is needed for unmerged/unreleased bugfix
    # https://github.com/ansible/ansible-modules-core/pull/3416
    force: true
