---


- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - bash
  - curl
  - grep
  - mktemp
  - openssl
  - sed

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
