---

- name: install
  include: install.yml
  when: role_letsencrypt_register_install is not defined

- name: install register
  set_fact:
    role_letsencrypt_register_install: ""
  when: role_letsencrypt_register_install is not defined

- include: config.yml

- include: ssl_gen.yml
  with_items: "{{ letsencrypt__domains.split('\n') }}"
  when: item != ""

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
