---

- name: install
  include: install.yml
  when: role_letsencrypt_register_install is not defined

- name: install register
  set_fact:
    role_letsencrypt_register_install: ""
  when: role_letsencrypt_register_install is not defined

- include: user_and_dirs.yml
- include: configure.yml
- include: cron_with_deploy_scripts.yml

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
