
# 1. проверить 80 и 443 порты если выключены то
# 2. создаём файлы сертификатов в папке где они должны быть сгенерированы
# 3. запускаем заглушку которая разложет самоподпистные сертификаты
# 4. после этого вешаем генерацию нормальных сертификатов
