---

- name: letsencrypt enabled
  systemd:
    enabled: yes
    state: started
    name: letsencrypt.timer
    daemon_reload: yes

- name: letsencrypt gen
  systemd:
    state: started
    name: letsencrypt
    daemon_reload: yes

